enum ApiKeyErrorCode {
  API_KEY_ALREADY_EXISTS = "API_KEY_ALREADY_EXISTS",
  API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND",
  REVOKED_API_KEY = "REVOKED_API_KEY",
  INVALID_API_KEY_CREDENTIALS = "INVALID_API_KEY_CREDENTIALS",
}

export default ApiKeyErrorCode;
