enum ApiKeyErrorCode {
  API_KEY_ALREADY_EXISTS = "API_KEY_ALREADY_EXISTS",
  API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND",
  API_KEY_INVALID = "API_KEY_INVALID",
  API_KEY_REVOKED = "API_KEY_REVOKED",
}

export default ApiKeyErrorCode;
