enum MerchantErrorCode {
  MERCHANT_NOT_FOUND = "MERCHANT_NOT_FOUND",
  MERCHANT_ACCESS_DENIED = "MERCHANT_ACCESS_DENIED",
  MERCHANT_INACTIVE = "MERCHANT_INACTIVE",
}

export default MerchantErrorCode;
