enum PaymentOrderErrorCode {
  PAYMENT_ORDER_NOT_FOUND = "PAYMENT_ORDER_NOT_FOUND",
  PAYMENT_ORDER_PAYMENT_PENDING = "PAYMENT_ORDER_PAYMENT_PENDING",
  PAYMENT_ORDER_EXPIRED = "PAYMENT_ORDER_EXPIRED",
  PAYMENT_ORDER_COMPLETED = "PAYMENT_ORDER_COMPLETED",
}

export default PaymentOrderErrorCode;
