const auth = {
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  EXPIRED_SESSION: "EXPIRED_SESSION",
  REVOKED_REFRESH_TOKEN: "REVOKED_REFRESH_TOKEN",
  MISSING_ACCESS_TOKEN: "MISSING_ACCESS_TOKEN",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
};

const apiErrorCode = {
  auth,
};

export default apiErrorCode;
