export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_REVOKED = "SESSION_REVOKED",
  INVALID_REQUEST = "INVALID_REQUEST",
  API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND",
}

export default ErrorCode;
