enum AuthErrorCode {
  MISSING_API_KEY_CREDENTIALS = "MISSING_API_KEY_CREDENTIALS",
  INVALID_API_KEY_CREDENTIALS = "INVALID_API_KEY_CREDENTIALS",
  REVOKED_API_KEY = "REVOKED_API_KEY",
  MISSING_FRONTEND_SECRET = "MISSING_FRONTEND_SECRET",
  INVALID_FRONTEND_SECRET = "INVALID_FRONTEND_SECRET",
}

export default AuthErrorCode;

