enum AuthErrorCode {
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  REVOKED_REFRESH_TOKEN = "REVOKED_REFRESH_TOKEN",
  EXPIRED_SESSION = "EXPIRED_SESSION",
  REVOKED_SESSION = "REVOKED_SESSION",
  INACTIVE_USER = "INACTIVE_USER",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN",
}

export default AuthErrorCode;
