enum MerchantErrorCode {
  MERCHANT_NOT_FOUND = "MERCHANT_NOT_FOUND",
  MERCHANT_INACTIVE = "MERCHANT_INACTIVE",
  MERCHANT_USER_MISMATCH = "MERCHANT_USER_MISMATCH",
}

export default MerchantErrorCode;
